### ISSUE TITLE
Refactor CDM field-size guardrail check reporting

### ISSUE THREAD

**Issue by pravinbhat** [datastax/cassandra-data-migrator#103]
CDM tool currently has utility to report on large single-fields that may break guardrail limits (e.g. Astra Size of values in a single column limit of 10MB). This functionality is currently broken and is difficult to maintain. 

Make this utility working again & Refactor the code to be much leaner & easy to maintain.

**Comment by mieslep** [comment]
This is completed with 4.0.0 release
