### ISSUE TITLE
Duplicate values observed in List cells when running Migrate or Validation multiple times

### ISSUE THREAD

**Issue by pravinbhat** [datastax/cassandra-data-migrator#138]
Duplicate values observed in List cells when running Migrate or Validation multiple times.

**Note:** This issue is a [bug in Cassandra](https://issues.apache.org/jira/browse/CASSANDRA-11368) (List inserts are not truly idempotent) & not really a CDM issue.

**Details of the issue:** As a side effect of the above C* bug, when CDM Migration or Validation (with auto-correct) is executed multiple times on the same table (this is not common, but can happen for various reasons), any existing list fields on target are overwritten again with the same timestamp (list values & timestamp from source), and this instead of replacing the full list duplicates all the entries on list. If you run the tool N times, the values would be duplicated N times.

**Priority/Customer Impact:** IHAC who is in midst of migrating several DSE 5.1 clusters to DSE 6.8. They are using ZDM + CDM for the same & are facing this issue. They understand that this is not a CDM issue, however they have asked us to provide a possible workaround/fix.

**Workaround/Fix:** The issue (duplicate cell values in List) happens only the timestamp is exactly same. If we increment the long epoch timestamp value by 1 (_which is 1 microseconds (1/1,000,000 second)_) & use this as the timestamp, the issue goes away. The timestamp value also is almost unchanged for humans and it does not create any (known) issues with migration (ZDM and/or CDM). Hence we will conditionally allow users to add an arbitrary long value (this should be typically 1) to the timestamp, which will allow them to workaround this issue.
<img width="1015" alt="Screenshot 2023-05-02 at 9 53 23 AM" src="https://user-images.githubusercontent.com/2746469/235905173-3bf1f642-2e4e-4bb0-bc84-4991833852a6.png">

**Comment by msmygit** [comment]
Addressed as part of PR #139
