### ISSUE TITLE
CDM tool checkpointing is not working once its only insert the partial partition details

### ISSUE THREAD

**Issue by ashu9041** [datastax/cassandra-data-migrator#298]
1. Checkpointing is not effective when CDM migration fails before or during the initial step of inserting all partitions inside the cdm_run_detail table. In this scenario, after initiating re-run process the CDM only migrates the partitions present in the cdm_run_detail table
2. The cdm_run_info table does not have a status column

**Comment by pravinbhat** [comment]
@ashu9041 This fix has been release as part of [version 4.3.8](https://github.com/datastax/cassandra-data-migrator/packages/1832128?version=4.3.8)
