### ISSUE TITLE
Use Secure Bundle as a Stream of Objects

### ISSUE THREAD

**Issue by Amit1509** [datastax/cassandra-data-migrator#316]
We need to modify the Secure Bundle implementation in cassandra data migrator to treat it as a stream of objects instead of loading it from a local copy. The current configuration includes sensitive passwords, which raises security concerns.

Proposed Solution:
1. We will use secure bundle in which config.json file will not contains the passwords.
2. Update the programming logic to accept these passwords as arguments.
3. Temporarily update the config.json during runtime to use the passwords.
4. Ensure that the passwords are not saved back into the system after usage.

This approach will enhance security while allowing us to utilize the Secure Bundle effectively.

**Comment by msmygit** [comment]
@Amit1509, I want to answer this concern,
> The current configuration includes sensitive passwords, which raises security concerns

Having just the [secure connect bundle (SCB)](https://docs.datastax.com/en/astra-db-serverless/drivers/secure-connect-bundle.html) in itself will *not* give anyone access to your Astra resources. It also *requires* one to have [the token](https://docs.datastax.com/en/astra-db-serverless/administration/manage-application-tokens.html) to access Astra resources.
