### ISSUE TITLE
README link to Spark 2.4.8 is a 404

### ISSUE THREAD

**Issue by johnsmartco** [datastax/cassandra-data-migrator#7]
In the README, https://github.com/datastax/cassandra-data-migrator/blob/main/README.md, the link to Spark 2.4.8 is a 404.  

https://downloads.apache.org/spark/spark-2.4.8/

Should it now point to one of the 3.x.x version listed on https://downloads.apache.org/spark/ ?

**Comment by pravinbhat** [comment]
@johnsmartco The broken link to Spark 2.4.8 has been corrected
