### ISSUE TITLE
Ability to stop/kill & resume the job 

### ISSUE THREAD

**Issue by pravinbhat** [datastax/cassandra-data-migrator#89]
The tool should have ability to resume the job from the point of previous exit. Customers may want to kill a running job (to change throttling speed, etc.), or sometimes a long running job may get killed for various reasons (vm restart, etc.). The tool should write partitions that have been processed and use it as an input during a future run to exclude migrated partitions.

**Comment by zhaogxd** [comment]
This is a very useful feature for large clusters. May I ask if it is on your roadmap?

**Comment by pravinbhat** [comment]
@zhaogxd This feature has been implemented & now available as part of release 4.3.0
